version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbp:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuserp
      POSTGRES_PASSWORD: mypasswordp
      POSTGRES_DB: mydatabasep
    ports:
      - "5433:5432"
    volumes:
      - postgres_datap:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5003:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    restart: always

  webp:
    build: .
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://myuserp:mypasswordp@dbp:5432/mydatabasep
    depends_on:
      - dbp
    command: python appp.py  # Ejecuta el archivo para productos
    restart: always
  webp2:
    build: .
    ports:
      - "5002:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    command: python applogin.py
    restart: always
  frontend:
    build: ./front_end
    ports:
      - "3000:3000"

  auth2fa:
    build: .
    ports:
      - "5004:5000"
    environment:
      DATABASE_URL: postgresql://authuser:authpass@auth-db:5432/authdb
    depends_on:
      - auth-db
    command: python authlogin.py  # 👈 Aquí defines el comando de ejecución


  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    volumes:
      - auth_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_datap:
  auth_data: